### PR TITLE
Vulnerability scan on push switch added

### PR DESCRIPTION
**Pull request by georgpet**
* Image tag mutability switch added

* Tags on the resource enabled

### CODE REVIEW

**Comment by mikael-lindstrom** [comment]
Currently tests only run on branches and not forks. I have given you write access, could you create a new branch in this repo and make a PR from there so the tests can trigger?

**Comment by itsdalmo** [comment]
> Currently tests only run on branches and not forks. I have given you write access, could you create a new branch in this repo and make a PR from there so the tests can trigger?

An alternative way now that Github Actions are out of beta (which I believe is how forks are intended to work) is to enable Github Actions in the fork itself. So in this case he should be able to enable Github Actions by visiting: https://github.com/georgpet/terraform-aws-ecr/actions and clicking enable.

**Comment by georgpet** [comment]
As per @itsdalmo advice I enabled the Actions in my repo and it worked: https://github.com/georgpet/terraform-aws-ecr/runs/479411759?check_suite_focus=true

**Comment by itsdalmo** [comment]
Seems like the commit status is not being picked up from the fork, so tests are not passing in the PR even though the workflow has been run in the fork and passes for the latest commit. Will give you write access so that the PR can be created from a branch instead of a PR 👍

**Comment by georgpet** [comment]
I'm closing this PR in favor of the next one, that will be created from local branch.

**Pull request closed without merging**
